- hosts: localhost
  #become: yes
  tasks: 
    - name: Deploying Application pods...
      shell: | 
         if [ `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep proj2 | wc -l` -gt 0 ]; then  
            echo "deleteing previous application deployment"
            kubectl delete deployment `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep proj2`
            echo "creating new application deployment"
            kubectl create deployment proj2 --image=nikhiltr1/proj2:{{ build }}
         else 
            echo "Deploying proj2 Application"
            kubectl create deployment proj2 --image=nikhiltr1/proj2:{{ build }}
         fi
    - name: deploying service
      shell: |
         if [ `kubectl get svc | grep proj2  | awk '{print $1}' | wc -l` -gt 0 ]; then
            echo "app service found, No actions taken"
            #kubectl delete svc `kubectl get svc | grep proj2 | awk '{print $1}'`
         else
            echo "Creating App Services"
            kubectl expose deployment proj2 --name proj2 --type NodePort --port 80 --node-port 30023
         fi
    - name: increase replicas 
      shell: kubectl scale deploy proj2 --replicas=2
      
    #- name: deploy app
    #  shell: kubectl create deployment projapp --image=nikhiltr1/projapp:{{ build }}
    #- name: deploy service
    #  shell: kubectl expose deployment projapp --name projapp --type NodePort --port 80 --target-port 8080
